import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {AppSidebar} from "@/components/AppSidebar";
import {ThemeProvider} from "next-themes";
import React from "react";
import {SidebarProvider} from "@/components/ui/sidebar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider>
                <div className="flex min-h-screen w-full">
                    <AppSidebar/>
                    <main className="flex-1 w-full min-w-0">
                        <div className="p-4 md:p-6 lg:p-8 w-full">
                            <div className="w-full max-w-[1400px] mx-auto">
                                {children}
                            </div>
                        </div>
                    </main>
                </div>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
