'use client'
// app/layout.tsx
import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { AppSidebar } from "@/components/AppSidebar"
import { ThemeProvider } from "next-themes"
import React from "react"
import { SidebarProvider } from "@/components/ui/sidebar"
import { WalletConfiguration } from "@/components/WalletConfiguration"
import { usePathname } from 'next/navigation'

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
})

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
})

// Metadata needs to be moved to a separate server component
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

function RootLayoutClient({
                              children,
                          }: Readonly<{
    children: React.ReactNode
}>) {
    const pathname = usePathname()
    const isHomePage = pathname === '/'

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WalletConfiguration>
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
            >
                {isHomePage ? (
                    // Login page layout without sidebar
                    <main className="flex-1 w-full min-w-0">
                        <div className="w-full h-screen">
                            {children}
                        </div>
                    </main>
                ) : (
                    // Regular app layout with sidebar
                    <SidebarProvider>
                        <div className="flex min-h-screen w-full">
                            <AppSidebar/>
                            <main className="flex-1 w-full min-w-0">
                                <div className="p-4 md:p-6 lg:p-8 w-full">
                                    <div className="w-full max-w-[1400px] mx-auto">
                                        {children}
                                    </div>
                                </div>
                            </main>
                        </div>
                    </SidebarProvider>
                )}
            </ThemeProvider>
        </WalletConfiguration>
        </body>
        </html>
    )
}

export default RootLayoutClient